# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAgregarProveedor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregarProveedor(object):
    def setupUi(self, AgregarProveedor):
        AgregarProveedor.setObjectName("AgregarProveedor")
        AgregarProveedor.setEnabled(True)
        AgregarProveedor.resize(336, 324)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Data/ruhrpumpen.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AgregarProveedor.setWindowIcon(icon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AgregarProveedor.sizePolicy().hasHeightForWidth())
        AgregarProveedor.setSizePolicy(sizePolicy)
        AgregarProveedor.setMinimumSize(QtCore.QSize(336, 324))
        AgregarProveedor.setMaximumSize(QtCore.QSize(336, 324))
        AgregarProveedor.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(AgregarProveedor)
        self.centralwidget.setObjectName("centralwidget")
        self.labelNombre = QtWidgets.QLabel(self.centralwidget)
        self.labelNombre.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.labelNombre.setObjectName("labelNombre")
        self.labelApellido = QtWidgets.QLabel(self.centralwidget)
        self.labelApellido.setGeometry(QtCore.QRect(190, 20, 47, 13))
        self.labelApellido.setObjectName("labelApellido")
        self.labelEmail = QtWidgets.QLabel(self.centralwidget)
        self.labelEmail.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.labelEmail.setObjectName("labelEmail")
        self.labelEmpresa = QtWidgets.QLabel(self.centralwidget)
        self.labelEmpresa.setGeometry(QtCore.QRect(20, 120, 47, 13))
        self.labelEmpresa.setObjectName("labelEmpresa")
        self.comboBoxTipo = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxTipo.setGeometry(QtCore.QRect(20, 190, 121, 22))
        self.comboBoxTipo.setObjectName("comboBoxTipo")
        self.comboBoxTipo.addItem("")
        self.comboBoxTipo.addItem("")
        self.comboBoxTipo.addItem("")
        self.comboBoxTipo.addItem("")
        self.labelTipo = QtWidgets.QLabel(self.centralwidget)
        self.labelTipo.setGeometry(QtCore.QRect(20, 170, 47, 13))
        self.labelTipo.setObjectName("labelTipo")
        self.labelPais = QtWidgets.QLabel(self.centralwidget)
        self.labelPais.setGeometry(QtCore.QRect(190, 170, 47, 13))
        self.labelPais.setObjectName("labelPais")
        self.comboBoxPais = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxPais.setGeometry(QtCore.QRect(190, 190, 121, 22))
        self.comboBoxPais.setObjectName("comboBoxPais")
        self.comboBoxPais.addItem("")
        self.comboBoxPais.addItem("")
        self.pushButtonAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAgregar.setGeometry(QtCore.QRect(30, 250, 75, 23))
        self.pushButtonAgregar.setObjectName("pushButtonAgregar")
        self.pushButtonLimpiar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLimpiar.setGeometry(QtCore.QRect(130, 250, 75, 23))
        self.pushButtonLimpiar.setObjectName("pushButtonLimpiar")
        self.pushButtonCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCancelar.setGeometry(QtCore.QRect(230, 250, 75, 23))
        self.pushButtonCancelar.setObjectName("pushButtonCancelar")
        self.lineEditNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNombre.setGeometry(QtCore.QRect(20, 40, 113, 20))
        self.lineEditNombre.setObjectName("lineEditNombre")
        self.lineEditApellido = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditApellido.setGeometry(QtCore.QRect(190, 40, 113, 20))
        self.lineEditApellido.setObjectName("lineEditApellido")
        self.lineEditEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditEmail.setGeometry(QtCore.QRect(20, 90, 281, 20))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditEmpresa = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditEmpresa.setGeometry(QtCore.QRect(20, 140, 113, 20))
        self.lineEditEmpresa.setObjectName("lineEditEmpresa")
        AgregarProveedor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AgregarProveedor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 336, 21))
        self.menubar.setObjectName("menubar")
        AgregarProveedor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AgregarProveedor)
        self.statusbar.setObjectName("statusbar")
        AgregarProveedor.setStatusBar(self.statusbar)

        self.retranslateUi(AgregarProveedor)
        QtCore.QMetaObject.connectSlotsByName(AgregarProveedor)

    def retranslateUi(self, AgregarProveedor):
        _translate = QtCore.QCoreApplication.translate
        AgregarProveedor.setWindowTitle(_translate("AgregarProveedor", "Agregar Proveedor"))
        self.labelNombre.setText(_translate("AgregarProveedor", "Nombre"))
        self.labelApellido.setText(_translate("AgregarProveedor", "Apellido"))
        self.labelEmail.setText(_translate("AgregarProveedor", "Email"))
        self.labelEmpresa.setText(_translate("AgregarProveedor", "Empresa"))
        self.comboBoxTipo.setItemText(0, _translate("AgregarProveedor", "Elija el tipo..."))
        self.comboBoxTipo.setItemText(1, _translate("AgregarProveedor", "Motores"))
        self.comboBoxTipo.setItemText(2, _translate("AgregarProveedor", "Sellos"))
        self.comboBoxTipo.setItemText(3, _translate("AgregarProveedor", "Acoples"))
        self.labelTipo.setText(_translate("AgregarProveedor", "Tipo"))
        self.labelPais.setText(_translate("AgregarProveedor", "Pais"))
        self.comboBoxPais.setItemText(0, _translate("AgregarProveedor", "Elija el pais..."))
        self.comboBoxPais.setItemText(1, _translate("AgregarProveedor", "Argentina"))
        self.pushButtonAgregar.setText(_translate("AgregarProveedor", "Agregar"))
        self.pushButtonLimpiar.setText(_translate("AgregarProveedor", "Limpiar"))
        self.pushButtonCancelar.setText(_translate("AgregarProveedor", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarProveedor = QtWidgets.QMainWindow()
    ui = Ui_AgregarProveedor()
    ui.setupUi(AgregarProveedor)
    AgregarProveedor.show()
    sys.exit(app.exec_())
