# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaOpciones.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaOpciones(object):
    def setupUi(self, VentanaOpciones):
        VentanaOpciones.setObjectName("VentanaOpciones")
        VentanaOpciones.resize(455, 262)
        VentanaOpciones.setMinimumSize(QtCore.QSize(455, 262))
        VentanaOpciones.setMaximumSize(QtCore.QSize(455, 262))
        self.centralwidget = QtWidgets.QWidget(VentanaOpciones)
        self.centralwidget.setObjectName("centralwidget")
        self.labelEmailUsuario = QtWidgets.QLabel(self.centralwidget)
        self.labelEmailUsuario.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.labelEmailUsuario.setObjectName("labelEmailUsuario")
        self.labelContrasena = QtWidgets.QLabel(self.centralwidget)
        self.labelContrasena.setGeometry(QtCore.QRect(240, 20, 61, 16))
        self.labelContrasena.setObjectName("labelContrasena")
        self.lineEditEmailUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditEmailUsuario.setGeometry(QtCore.QRect(20, 40, 201, 20))
        self.lineEditEmailUsuario.setObjectName("lineEditEmailUsuario")
        self.lineEditContrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditContrasena.setGeometry(QtCore.QRect(240, 40, 171, 20))
        self.lineEditContrasena.setInputMask("")
        self.lineEditContrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditContrasena.setObjectName("lineEditContrasena")
        self.labelServidor = QtWidgets.QLabel(self.centralwidget)
        self.labelServidor.setGeometry(QtCore.QRect(20, 110, 51, 16))
        self.labelServidor.setObjectName("labelServidor")
        self.lineEditServidor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditServidor.setEnabled(False)
        self.lineEditServidor.setGeometry(QtCore.QRect(20, 130, 201, 20))
        self.lineEditServidor.setObjectName("lineEditServidor")
        self.checkBoxServidor = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxServidor.setGeometry(QtCore.QRect(20, 80, 101, 17))
        self.checkBoxServidor.setObjectName("checkBoxServidor")
        self.labelPuerto = QtWidgets.QLabel(self.centralwidget)
        self.labelPuerto.setGeometry(QtCore.QRect(240, 110, 51, 16))
        self.labelPuerto.setObjectName("labelPuerto")
        self.lineEditPuerto = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPuerto.setEnabled(False)
        self.lineEditPuerto.setGeometry(QtCore.QRect(240, 130, 51, 20))
        self.lineEditPuerto.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEditPuerto.setObjectName("lineEditPuerto")
        self.checkBoxContrasena = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxContrasena.setGeometry(QtCore.QRect(240, 80, 121, 17))
        self.checkBoxContrasena.setObjectName("checkBoxContrasena")
        self.pushButtonGuardar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGuardar.setGeometry(QtCore.QRect(100, 190, 81, 31))
        self.pushButtonGuardar.setObjectName("pushButtonGuardar")
        self.pushButtonCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCancelar.setGeometry(QtCore.QRect(270, 190, 81, 31))
        self.pushButtonCancelar.setObjectName("pushButtonCancelar")
        VentanaOpciones.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaOpciones)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 21))
        self.menubar.setObjectName("menubar")
        VentanaOpciones.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaOpciones)
        self.statusbar.setObjectName("statusbar")
        VentanaOpciones.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaOpciones)
        QtCore.QMetaObject.connectSlotsByName(VentanaOpciones)

    def retranslateUi(self, VentanaOpciones):
        _translate = QtCore.QCoreApplication.translate
        VentanaOpciones.setWindowTitle(_translate("VentanaOpciones", "Opciones"))
        self.labelEmailUsuario.setText(_translate("VentanaOpciones", "Email:"))
        self.labelContrasena.setText(_translate("VentanaOpciones", "Contraseña:"))
        self.labelServidor.setText(_translate("VentanaOpciones", "Servidor:"))
        self.checkBoxServidor.setText(_translate("VentanaOpciones", "Elegir el Servidor"))
        self.labelPuerto.setText(_translate("VentanaOpciones", "Puerto:"))
        self.checkBoxContrasena.setText(_translate("VentanaOpciones", "Mostrar contraseña"))
        self.pushButtonGuardar.setText(_translate("VentanaOpciones", "Guardar"))
        self.pushButtonCancelar.setText(_translate("VentanaOpciones", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaOpciones = QtWidgets.QMainWindow()
    ui = Ui_VentanaOpciones()
    ui.setupUi(VentanaOpciones)
    VentanaOpciones.show()
    sys.exit(app.exec_())
